
from typing import Tuple
from ..prompt import Prompt

import os
from openai import OpenAI

from ..util import evaluate_response

deepSeekClient = OpenAI(api_key=os.environ.get('DEEPSEEK_API_KEY'), base_url="https://api.deepseek.com")

class Deepseek:
    model = "deepseek-reasoner"

    def ask(self, prompt: Prompt) -> Tuple[bool, str]:
        response = deepSeekClient.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert news analyst performing a content credibility assessment.\n"
                            "Do not verify external facts, but analyze the internal logic, tone, and style.\n"
                            "\n"
                            "GUIDELINES FOR REASONING:\n"
                            "1. **Distinguish Intent:** Is the article trying to inform (Journalism) or manipulate (Propaganda/Clickbait)?\n"
                            "2. **Evaluate Evidence:** \n"
                            "   - Missing sources in a short summary are NORMAL -> Lean True.\n"
                            "   - Missing sources for extraordinary or shocking claims are SUSPICIOUS -> Lean Fake.\n"
                            "3. **Tone Analysis:** heavily emotional vocabulary (e.g., 'SHOCKING', 'DESTROYED') suggests Fake.\n"
                            "\n"
                            "DECISION LOGIC:\n"
                            "- **True:** Neutral tone, plausible claims, standard reporting style (even if some citations are implicit).\n"
                            "- **Fake:** Manipulative tone, logical fallacies, contradictions, or extraordinary claims without evidence.\n"
                            "\n"
                            "If the article looks like a standard news snippet but lacks citations due to brevity, mark it as TRUE.\n"
                            "\n"
                            "Output format (JSON):\n"
                            "{\"classification\": \"True\" | \"Fake\", \"explanation\": \"...\"}"
                    )
                },
                {"role": "user", "content": prompt.input}
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if not text:
            raise ValueError("No response from DeepSeek.")

        prompt.bot_output_text = text
        prompt.bot_evaluation = evaluate_response(text)

        return prompt.bot_evaluation, text


    def evaluate_output(self, prompt: Prompt):
            response = deepSeekClient.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content":
                        "You are evaluating a content-based True/Fake classification generated by another assistant.\n"
                        "Check ONLY whether the explanation is consistent with the label and refers to concrete linguistic features of the article.\n"
                        "Ignore tone and style unless objective claims are asserted and contradicted by evidence.\n"
                        "Do you agree with the assessment?\n"
                        "Start your response strictly with 'True' (if you agree) or 'False' (if you disagree).\n" 
                        "Follow with a short, factual explanation."
                    },
                    {"role": "user", "content": prompt.response}
                ],
                stream=False
            )

            text = response.choices[0].message.content
            if text is None:
                raise ValueError("No response from DeepSeek (evaluate_output).")

            text_clean = text.strip().lower()

            if text_clean.startswith("true") or text_clean.startswith("accept") or text_clean.startswith("yes"):
                return True, text
                
            if text_clean.startswith("false") or text_clean.startswith("reject") or text_clean.startswith("no"):
                return False, text

            raise ValueError(f"DeepSeek evaluate_output format error. Got: {text[:50]}...")

    def rewrite_output(self, prompt: Prompt):
        response = deepSeekClient.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content":
                    "You are rewriting a content-based True/Fake classification that was previously rejected.\n"
                    "Your task:\n"
                    "- Improve only the reasoning / explanation.\n"
                    "- Base the explanation ONLY on factual accuracy and verifiable-style claims from the article's content.\n"
                    "- Do NOT change the True/False label; keep the original classification exactly.\n"
                    "- Do NOT introduce new claims not present in the article.\n"
                    "Output ONLY:"
                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""
                },
                {"role": "user", "content":
                    f"The previous reasoning was rejected. Rewrite a clearer and logically consistent explanation.\n"
                    f"Original classification: {prompt.bot_evaluation}\n"
                    f"Previous reasoning:\n{prompt.bot_output_text}"
                }
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek (rewrite_output).")
        # Enforce keeping the original classification to avoid flip-flopping
        return prompt.bot_evaluation, text