
from typing import Tuple
from classes.prompt import Prompt

import os
from openai import OpenAI

from ..util import evaluate_response

deepSeekClient = OpenAI(api_key=os.environ.get('DEEPSEEK_API_KEY'), base_url="https://api.deepseek.com")

class Deepseek:
    
    model = "deepseek-reasoner"

    def ask(self, prompt: Prompt) -> Tuple[bool, str]:
        response = deepSeekClient.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content":
                    "You are classifying a news article in a content-based sense.\n"
                    "Criterion: Focus on factual accuracy and whether the article presents speculative or opinion statements as established facts without verifiable evidence. Ignore tone and style unless the text asserts objective claims contradicted by evidence.\n"
                    "Classify the article as **True** or **Fake**.\n"
                    "Definitions:\n"
                    "\"True\" = the article reports facts or clearly attributes claims (e.g., \"X claims...\") without presenting speculation/opinion as verified facts.\n"
                    "\"Fake\" = the article presents speculative/opinion statements as established facts without verifiable evidence, or asserts objective claims contradicted by evidence.\n"

                    "Output ONLY:"

                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""

                },
                {"role": "user", "content": prompt.input}
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek.")
        
        return evaluate_response(text), text

    def evaluate_output(self, prompt: Prompt):
        response = deepSeekClient.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content":
                    "You are evaluating a content-based True/Fake classification generated by another assistant."
                    "Check whether the classification correctly reflects the article based on factual accuracy AND whether it presents speculative/opinion statements as established facts without verifiable evidence."
                    "Ignore tone and style unless objective claims are asserted and contradicted by evidence."
                    "Return 'Accept' if the classification is correct, 'Reject' if it is incorrect. Provide a short, factual explanation."
                },
                {"role": "user", "content": prompt.response}
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek (evaluate_output).")

        text_lower = text.lower()
        
        if text_lower.startswith("accept"):
            return True, text
        if text_lower.startswith("reject"):
            return False, text

        raise ValueError("DeepSeek evaluate_output did not return Accept or Reject:\n" + text)

    def rewrite_output(self, prompt: Prompt):
        response = deepSeekClient.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content":
                    "You are rewriting a content-based True/Fake classification that was previously rejected.\n"
                    "Your task:\n"
                    "- Improve only the reasoning / explanation.\n"
                    "- Base the explanation ONLY on factual accuracy and verifiable-style claims from the article's content.\n"
                    "- Do NOT change the True/False label; keep the original classification exactly.\n"
                    "Output ONLY:"
                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""
                },
                {"role": "user", "content":
                    f"The previous reasoning was rejected. Rewrite a clearer and logically consistent explanation.\n"
                    f"Original classification: {prompt.bot_evaluation}\n"
                    f"Previous reasoning:\n{prompt.bot_output_text}"
                }
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek (rewrite_output).")
        # Enforce keeping the original classification to avoid flip-flopping
        return prompt.bot_evaluation, text