
from typing import Tuple
from classes.prompt import Prompt

import os
from openai import OpenAI

from ..util import evaluate_response

deepSeekClient = OpenAI(api_key=os.environ.get('DEEPSEEK_API_KEY'), base_url="https://api.deepseek.com")

class Deepseek:

    def ask(self, prompt: Prompt) -> Tuple[bool, str]:
        response = deepSeekClient.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content":
                    # "You are a fact-checking assistant. Your goal is to determine whether a given news headline is true or fake based on real-world information. Answer clearly and briefly with 'True' or 'Fake' and a short explanation."
                    "Based on:"

                    "- The extracted claims"
                    "- Internal consistency"
                    "- Manipulative language level"

                    "Classify the article as **True** or **Fake** in a content-based sense."

                    "Definitions:"
                    "\"True\" = the text appears internally coherent, fact-like, and based on verifiable-style statements even if actual truth cannot be checked."
                    "\"Fake\" = the text contains clear signs of fabrication, internal contradictions, strong manipulative tone, or unreliable narrative."

                    "Output ONLY:"

                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""

                },
                {"role": "user", "content": prompt.input}
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek.")
        
        return evaluate_response(text), text

    def evaluate_output(self, prompt: Prompt):
        response = deepSeekClient.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content":
                    "You are evaluating a content-based True/Fake classification generated by another assistant."
                    "Check whether the classification correctly reflects the actual content of the news article. "
                    "Do NOT base your judgement on tone, bias, or subjective interpretation; focus ONLY on factual accuracy."
                    "Return 'Accept' if the classification is correct, 'Reject' if it is incorrect. Provide a short, factual explanation."
                },
                {"role": "user", "content": prompt.response}
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek (evaluate_output).")

        text_lower = text.lower()
        
        if text_lower.startswith("accept"):
            return True, text
        if text_lower.startswith("reject"):
            return False, text

        raise ValueError("DeepSeek evaluate_output did not return Accept or Reject:\n" + text)

    def rewrite_output(self, prompt: Prompt):
        response = deepSeekClient.chat.completions.create(
            model="deepseek-chat",
            messages=[
                {"role": "system", "content":
                    "You are rewriting a content-based True/Fake classification that was previously rejected.\n"
                    "Your task:\n"
                    "- Keep the original label exactly as it is (True or Fake).\n"
                    "- Improve only the reasoning / explanation.\n"
                    "- Base the explanation ONLY on:\n"
                    "  - extracted claims\n"
                    "  - internal consistency\n"
                    "  - manipulative language\n"
                    "Output ONLY:\n"
                    "\"<Original Label>\"\n"
                    "\"Explanation: <1 sentence>\""
                },
                {"role": "user", "content":
                    f"The previous reasoning was rejected. Rewrite a clearer and logically consistent explanation.\n"
                    f"Original classification: {prompt.bot_evaluation}\n"
                    f"Previous reasoning:\n{prompt.bot_output_text}"
                }
            ],
            stream=False
        )

        text = response.choices[0].message.content
        if text is None:
            raise ValueError("No response from DeepSeek (rewrite_output).")

        return evaluate_response(text), text

