
from typing import Tuple
from classes.prompt import Prompt
import os

from google import genai
from google.genai import types

from ..util import evaluate_response

geminiClient = genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))

class Gemini:
    
    model = "gemini-2.5-flash"
    
    def ask(self, prompt: Prompt) -> Tuple[bool, str]:
        print("Asking Gemini...")
        response = geminiClient.models.generate_content(
            model=self.model,
            contents=prompt.input,
            config=types.GenerateContentConfig(
                # system_instruction="You are a fact-checking assistant. Your goal is to determine whether a given news headline is true or fake based on real-world information. \nAnswer clearly and briefly with 'True' or 'Fake' and a short explanation. Avoid writing **True** or **Fake**."
                system_instruction=(
                    "Based on:"

                    "- The extracted claims"
                    "- Internal consistency"
                    "- Manipulative language level"

                    "Classify the article as **True** or **Fake** in a content-based sense."

                    "Definitions:"
                    "\"True\" = the text appears internally coherent, fact-like, and based on verifiable-style statements even if actual truth cannot be checked."
                    "\"Fake\" = the text contains clear signs of fabrication, internal contradictions, strong manipulative tone, or unreliable narrative."

                    "Output ONLY:"

                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""
                )
            )
        )
        
        if response.text is None:
            raise ValueError("No response from Gemini.")
        
        prompt.bot_output_text = response.text
        prompt.bot_evaluation = evaluate_response(response.text)
        
        return (prompt.bot_evaluation, response.text)
    
    def evaluate_output(self, prompt: Prompt):
        response = geminiClient.models.generate_content(
            model=self.model,
            contents=prompt.response,
            config=types.GenerateContentConfig(
                system_instruction=(
                    "You are evaluating a content-based True/Fake classification generated by another assistant."

                    "- Check whether the classification (\"True\" or \"Fake\") is correct given the text."
                    "- If the classification correctly reflects the content, return \"Accept\"."
                    "- If the classification is wrong or misaligned with the content, return \"Reject\"."
                    "- Provide a very short explanation."
                )
            )
        )
        
        if response.text is None:
            raise ValueError("No response from Gemini (evaluate_output).")
        
        text = response.text.lower()
        accepted = text.startswith("accept")
        return accepted, response.text
    
    def rewrite_output(self, prompt: Prompt):
        response = geminiClient.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"The previous reasoning was rejected. Rewrite a better fact-checking analysis.\n\nPrevious reasoning:\n{prompt.bot_output_text}",
            config=types.GenerateContentConfig(
                system_instruction=(
                "You are rewriting a content-based True/Fake classification that was previously rejected."

                "Your task:"
                "- Produce a clearer, logically consistent classification"
                "- Base the evaluation ONLY on:"
                "- extracted claims"
                "- internal consistency"
                "- manipulative language"
                "- Apply the provided definitions:"
                "\"True\" = coherent, fact-like, plausible  "
                "\"Fake\" = contradictory, manipulative, fabricated tone"

                "Output ONLY:"

                "True/Fake"  
                "Explanation: <1 sentence>"
                )
            )
        )
        text = response.text
        
        if text is None:
            raise ValueError("No response from Gemini (rewrite_output).")
        
        return evaluate_response(text), text