
from typing import Tuple
from ..prompt import Prompt
import os

from google import genai
from google.genai import types

from ..util import evaluate_response

geminiClient = genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))

class Gemini:
    
    model = "gemini-2.5-flash"
    
    def ask(self, prompt: Prompt) -> Tuple[bool, str]:
        print("Asking Gemini...")
        response = geminiClient.models.generate_content(
            model=self.model,
            contents=prompt.input,
            config=types.GenerateContentConfig(
                system_instruction=(
                    "You are classifying a news article in a content-based sense.\n"
                    "Criterion: Focus on factual accuracy and whether the article presents speculative or opinion statements as established facts without verifiable evidence. Ignore tone and style unless the text asserts objective claims contradicted by evidence.\n"
                    "Classify the article as **True** or **Fake**.\n"
                    "Definitions:\n"
                    "\"True\" = the article reports facts or clearly attributes claims (e.g., \"X claims...\") without presenting speculation/opinion as verified facts.\n"
                    "\"Fake\" = the article presents speculative/opinion statements as established facts without verifiable evidence, or asserts objective claims contradicted by evidence.\n"

                    "Output ONLY:"

                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""
                )
            )
        )
        
        if response.text is None:
            raise ValueError("No response from Gemini.")
        
        prompt.bot_output_text = response.text
        prompt.bot_evaluation = evaluate_response(response.text)
        
        return (prompt.bot_evaluation, response.text)
    
    def evaluate_output(self, prompt: Prompt):
        response = geminiClient.models.generate_content(
            model=self.model,
            contents=prompt.response,
            config=types.GenerateContentConfig(
                system_instruction=(
                    "You are evaluating a content-based True/Fake classification generated by another assistant."
                    "Check whether the classification correctly reflects the article based on factual accuracy AND whether it presents speculative/opinion statements as established facts without verifiable evidence."
                    "Ignore tone and style unless objective claims are asserted and contradicted by evidence."
                    "Return 'Accept' if the classification is correct, 'Reject' if it is incorrect. Provide a short, factual explanation."
                )
            )
        )
        
        if response.text is None:
            raise ValueError("No response from Gemini (evaluate_output).")
        
        text = response.text.lower()
        accepted = text.startswith("accept")
        return accepted, response.text
    
    def rewrite_output(self, prompt: Prompt):
        response = geminiClient.models.generate_content(
            model="gemini-2.5-flash",
            contents= (
                    f"The previous reasoning was rejected. Rewrite a clearer and logically consistent explanation.\n"
                    f"Original classification: {prompt.bot_evaluation}\n"
                    f"Previous reasoning:\n{prompt.bot_output_text}"),
            config=types.GenerateContentConfig(
                system_instruction=(
                    "You are rewriting a content-based True/Fake classification that was previously rejected.\n"
                    "Your task:\n"
                    "- Improve only the reasoning / explanation.\n"
                    "- Base the explanation ONLY on factual accuracy and verifiable-style claims from the article's content.\n"
                    "- Do NOT change the True/False label; keep the original classification exactly.\n"
                     "Output ONLY:"
                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""
                )
            )
        )
        text = response.text
        
        if text is None:
            raise ValueError("No response from Gemini (rewrite_output).")
        # Enforce keeping the original classification to avoid flip-flopping
        return prompt.bot_evaluation, text