
from typing import Any,Tuple
from ..prompt import Prompt
import os

from google import genai
from google.genai import types

from ..util import evaluate_response

geminiClient = genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))

class Gemini:
    model = "gemini-2.5-flash"

    def ask(self, prompt: Prompt) -> Tuple[bool, str]:
        config = types.GenerateContentConfig(
            system_instruction=(
                "You are an expert news analyst performing a content credibility assessment.\n"
                "Do not verify external facts, but analyze the internal logic, tone, and style.\n"
                "\n"
                "GUIDELINES FOR REASONING:\n"
                "1. **Distinguish Intent:** Is the article trying to inform (Journalism) or manipulate (Propaganda/Clickbait)?\n"
                "2. **Evaluate Evidence:** \n"
                "   - Missing sources in a short summary are NORMAL -> Lean True.\n"
                "   - Missing sources for extraordinary or shocking claims are SUSPICIOUS -> Lean Fake.\n"
                "3. **Tone Analysis:** heavily emotional vocabulary (e.g., 'SHOCKING', 'DESTROYED') suggests Fake.\n"
                "\n"
                "DECISION LOGIC:\n"
                "- **True:** Neutral tone, plausible claims, standard reporting style (even if some citations are implicit).\n"
                "- **Fake:** Manipulative tone, logical fallacies, contradictions, or extraordinary claims without evidence.\n"
                "\n"
                "If the article looks like a standard news snippet but lacks citations due to brevity, mark it as TRUE.\n"
                "\n"
                "Output format (JSON):\n"
                "{\"classification\": \"True\" | \"Fake\", \"explanation\": \"...\"}"
                )
        )

        response = geminiClient.models.generate_content(
            model=self.model,
            contents=prompt.input,
            config=config
        )

        if not response.text:
            raise ValueError("Empty Gemini response")

        prompt.bot_output_text = response.text
        prompt.bot_evaluation = evaluate_response(response.text)

        return prompt.bot_evaluation, response.text

    def evaluate_output(self, prompt: Prompt):
            response = geminiClient.models.generate_content(
                model=self.model,
                contents=prompt.response,
                config=types.GenerateContentConfig(
                    system_instruction=(
                        "You are evaluating a content-based True/Fake classification generated by another assistant.\n"
                        "Check ONLY whether the explanation is consistent with the label.\n"
                        "Do you agree with the assessment?\n"
                        "Start your response strictly with 'True' (if you agree) or 'False' (if you disagree).\n"
                        "Follow with a short, factual explanation."
                    )
                )
            )
            
            if not response.text:
                raise ValueError("No response from Gemini (evaluate_output).")
            
            text = response.text.strip().lower()
            
            if text.startswith("true") or text.startswith("accept") or text.startswith("yes"):
                return True, response.text
                
            if text.startswith("false") or text.startswith("reject") or text.startswith("no"):
                return False, response.text
                
            print(f"Warning: Gemini evaluate format unclear: {text[:20]}...")
            return False, response.text
    
    def rewrite_output(self, prompt: Prompt):
        response = geminiClient.models.generate_content(
            model="gemini-2.5-flash",
            contents= (
                    f"The previous reasoning was rejected. Rewrite a clearer and logically consistent explanation.\n"
                    f"Original classification: {prompt.bot_evaluation}\n"
                    f"Previous reasoning:\n{prompt.bot_output_text}"),
            config=types.GenerateContentConfig(
                system_instruction=(
                    "You are rewriting a content-based True/Fake classification that was previously rejected.\n"
                    "Your task:\n"
                    "- Improve only the reasoning / explanation.\n"
                    "- Base the explanation ONLY on factual accuracy and verifiable-style claims from the article's content.\n"
                    "- Do NOT change the True/False label; keep the original classification exactly.\n"
                    "- Do NOT introduce new claims not present in the article.\n"
                     "Output ONLY:"
                    "\"True/Fake\""  
                    "\"Explanation: <1 sentence>\""
                )
            )
        )
        text = response.text
        
        if text is None:
            raise ValueError("No response from Gemini (rewrite_output).")
        
        prompt.bot_output_text = text
        return prompt.bot_evaluation, text